### ISSUE TITLE
Identidade visual

### ISSUE THREAD

**Issue by h-pgy** [sepep-pmsp/site_smae#1]
# Configurar identidade visual

Identidade visual deve atender à identidade visual do SMAE

### dados para front-end

basear nesta página:
https://smae.appcivico.com/login

cores:
```less
@primary: #152741;
@amarelo: #F7C234;
@escuro: #061223;
@branco: #FFF;
@azul: #4074BF;
```

fonte:
```less
body {
  font-family: 'Roboto', sans-serif;
  font-size: 100%;
  font-size: 14px;
  line-height: 1.15;
  color: @primary;
  background: #ffffff;
  min-height: 100vh;
}
```
